services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
