'use client'
import {useState} from 'react'

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'
type Performer={name:string;type:string;hair_color:string;hair_style:string;glasses:boolean}
type Product={id:number;title:string;description:string;release_date:string;fanza_url:string;performers:Performer[];attributes:Record<string,any>}

export default function Home(){
 const [query,setQuery]=useState('');const [items,setItems]=useState<Product[]>([]);const [filters,setFilters]=useState<any>();const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [importUrl,setImportUrl]=useState('');const [importing,setImporting]=useState(false)
 async function search(){setLoading(true);setMessage('');try{const r=await fetch(API+'/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query})});const d=await r.json();setItems(d.results||[]);setFilters(d.filters)}catch{setMessage('APIに接続できません。バックエンドが起動しているか確認してね。')}finally{setLoading(false)}}
 async function seed(){await fetch(API+'/products/seed',{method:'POST'});setMessage('サンプル作品を登録したよ。検索してみて。')}
 async function importVideo(){if(!importUrl)return;setImporting(true);setMessage('取得を開始しているよ…');try{const r=await fetch(API+'/imports/missav',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:importUrl,analyze:true})});const job=await r.json();if(!r.ok)throw new Error(job.detail||'開始できませんでした');setMessage(`取得中：ジョブ ${job.id}`);const timer=setInterval(async()=>{const s=await fetch(API+'/imports/'+job.id).then(x=>x.json());if(s.status==='splitting'){setMessage('動画から代表シーンを抽出中…')}else if(s.status==='json_building'){setMessage('AIが検索用JSONを生成中…')}else if(s.status==='completed'){clearInterval(timer);setImporting(false);setMessage(`解析・DB登録完了：${s.title}（作品ID ${s.product_id}）`)}else if(s.status==='failed'){clearInterval(timer);setImporting(false);setMessage(`処理失敗：${s.error}`)}},2000)}catch(e){setImporting(false);setMessage(e instanceof Error?e.message:'取得に失敗しました')}}
 return <main><header><div className="headerActions"><a className="statusLink" href="/imports"><span>●</span> 取込状況を見る <b>→</b></a><a className="statusLink libraryLink" href="/videos"><span>◆</span> 読み込んだ動画 <b>→</b></a></div><div className="heroCopy"><div className="eyebrow">AI WORKS SEARCH</div><h1>作品を、<em>自然な言葉</em>で探す。</h1><p>条件を組み合わせて、あなたに合う作品を見つけよう。</p><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="例：黒髪でメガネ、ホテルが舞台の1人作品"/><button onClick={search}>{loading?'検索中…':'検索する'}</button></div><div className="quick"><span>試してみる：</span>{['黒髪 ロング','制服 学校','清楚系 スーツ'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div></div></header><section className="content"><div className="importer"><div><b>取得・AI解析・DB登録</b><small>公開作品URLを1件ずつ指定</small></div><input value={importUrl} onChange={e=>setImportUrl(e.target.value)} placeholder="https://missav..."/><button disabled={importing} onClick={importVideo}>{importing?'処理中…':'取り込む'}</button></div>{message&&<div className="notice">{message}</div>}{filters&&<div className="found">検索条件 <code>{JSON.stringify(filters)}</code><span>{items.length} 件</span></div>}<div className="grid">{items.map(p=><article className="resultCard" key={p.id}><div className="cover">{p.attributes?.場所?.[0]||'作品'}<small>{p.release_date?.slice(0,4)||'—'}</small></div><div className="cardbody"><h2>{p.title}</h2><p>{p.description}</p><div className="tags">{p.performers?.map(x=><span key={x.name}>{x.name}</span>)}{p.attributes?.衣装?.map((x:string)=><span key={x}>{x}</span>)}</div><a href={API+'/go/'+p.id} target="_blank">掲載元で詳細を見る →</a></div></article>)}</div>{!items.length&&!filters&&<div className="empty"><div>✦</div><h2>まずは作品データを登録しよう</h2><p>開発用のサンプル作品を登録して、検索の動きを確認できます。</p><button onClick={seed}>サンプルを登録</button></div>}</section></main>
}
